-- Trisakti Traders shared family retail ledger
-- Verified against Supabase project on 2026-09-20.
-- Client apps use the publishable key only. Never place service_role/secret keys in the APK.

create or replace function public.is_authorized_family_member()
returns boolean
language sql
stable
security invoker
set search_path = public
as $$
  select lower(coalesce((select auth.jwt() ->> 'email'), '')) in (
    'bajgaisandesh8@gmail.com',
    'arjunbajgai7@gmail.com'
  );
$$;

create table if not exists public.sales (
  id bigint generated by default as identity primary key,
  date date not null,
  amount numeric not null check (amount >= 0),
  product_cost numeric not null default 0 check (product_cost >= 0),
  payment_type text not null default 'CASH' check (payment_type in ('CASH','CREDIT','OTHER')),
  description text not null default '',
  notes text,
  recorded_by uuid references auth.users(id),
  created_at timestamptz not null default now()
);

create table if not exists public.expenses (
  id bigint generated by default as identity primary key,
  date date not null,
  amount numeric not null check (amount > 0),
  category text not null,
  description text not null default '',
  notes text,
  recorded_by uuid references auth.users(id),
  created_at timestamptz not null default now()
);

create table if not exists public.credit_customers (
  id bigint generated by default as identity primary key,
  name text not null,
  phone text not null default '',
  notes text not null default '',
  initial_credit numeric not null default 0 check (initial_credit >= 0),
  created_at timestamptz not null default now()
);

create table if not exists public.credit_transactions (
  id bigint generated by default as identity primary key,
  customer_id bigint not null references public.credit_customers(id) on delete cascade,
  date date not null,
  type text not null check (type in ('CREDIT','PAYMENT')),
  amount numeric not null check (amount > 0),
  description text not null default '',
  recorded_by uuid references auth.users(id),
  created_at timestamptz not null default now()
);

create table if not exists public.daily_closings (
  id bigint generated by default as identity primary key,
  date date not null unique,
  opening_cash numeric not null default 0,
  cash_sales numeric not null default 0,
  cash_expenses numeric not null default 0,
  credit_sales numeric not null default 0,
  credit_payments numeric not null default 0,
  expected_cash numeric not null default 0,
  actual_cash numeric not null default 0,
  difference numeric not null default 0,
  notes text,
  recorded_by uuid references auth.users(id),
  created_at timestamptz not null default now()
);

grant select, insert, update, delete on public.sales, public.expenses,
  public.credit_customers, public.credit_transactions, public.daily_closings
  to authenticated;

alter table public.sales enable row level security;
alter table public.expenses enable row level security;
alter table public.credit_customers enable row level security;
alter table public.credit_transactions enable row level security;
alter table public.daily_closings enable row level security;

drop policy if exists "family sales access" on public.sales;
create policy "family sales access" on public.sales
  for all to authenticated
  using (public.is_authorized_family_member())
  with check (public.is_authorized_family_member());

drop policy if exists "family expenses access" on public.expenses;
create policy "family expenses access" on public.expenses
  for all to authenticated
  using (public.is_authorized_family_member())
  with check (public.is_authorized_family_member());

drop policy if exists "family credit customers access" on public.credit_customers;
create policy "family credit customers access" on public.credit_customers
  for all to authenticated
  using (public.is_authorized_family_member())
  with check (public.is_authorized_family_member());

drop policy if exists "family credit transactions access" on public.credit_transactions;
create policy "family credit transactions access" on public.credit_transactions
  for all to authenticated
  using (public.is_authorized_family_member())
  with check (public.is_authorized_family_member());

drop policy if exists "family daily closings access" on public.daily_closings;
create policy "family daily closings access" on public.daily_closings
  for all to authenticated
  using (public.is_authorized_family_member())
  with check (public.is_authorized_family_member());
